apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
    - name: container-1
      image: ubuntu:18.04
      volumeMounts:
        - name: cache-volume
          mountPath: /cache
          subPath: cache1
        - name: hostpath-volume
          mountPath: /data
          readOnly: true
    - name: container-2
      image: ubuntu:18.04
      volumeMounts:
        - mountPath: /cache
          name: cache-volume
          subPath: cache2
  volumes:
    - name: cache-volume
      emptyDir: {}
    - name: hostpath-volume
      hostPath:
        path: /tmp/data



