@startuml
'https://plantuml.com/sequence-diagram
database "数据库\n(中心)"
queue DTS服务
database "数据库\n(非中心)"
participant "运行时服务\n(DTS客户端)"
database 分布式缓存
queue 消息队列
collections 运行时服务
autonumber
"数据库\n(中心)" ->"数据库\n(中心)" :订阅的数据表\n发生变化
"数据库\n(中心)" -> "DTS服务" :变化信息
"DTS服务" -> "数据库\n(非中心)" :同步变化
"DTS服务" -> "运行时服务\n(DTS客户端)" :发送变化信息
"运行时服务\n(DTS客户端)" -> "运行时服务\n(DTS客户端)" :过滤处理\n转化变化信息
"运行时服务\n(DTS客户端)" -> "分布式缓存" :刷新缓存
"分布式缓存" -> "运行时服务\n(DTS客户端)" :OK
"运行时服务\n(DTS客户端)" -> "消息队列": 发送本地\n缓存刷新消息
"消息队列" -> "运行时服务\n(DTS客户端)" :OK
"消息队列" -> "运行时服务" :推送消息
"运行时服务"->"运行时服务" :刷新本地缓存
"运行时服务"->"运行时服务" :记录日志
@enduml

